### ISSUE TITLE
Python version for environment on Apple Silicon

### ISSUE THREAD

**Issue by BoilerToad** [domschl/HuggingFaceGuidedTourForMac#1]
Getting the error ... "ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)" .  What version python was this tested with?

**Comment by domschl** [comment]
If you are using Homebrew, the default python is now 3.12, which is not yet support by many of the deep learning platforms. Install python 3.11 (`brew install python@3.11`) and either make it the default, or create an environment with python 3.11: (`python3.11 -m venv py311env && cd py311env && source bin/activate`).

In short, python 3.11 (or older) is required.

**Comment by BoilerToad** [comment]
That works ... thanks!

**Comment by BoilerToad** [comment]
Tested on Apple M3 Max w/64 GB RAM.. works well
